### ISSUE TITLE
HW1 is ready for grading

### ISSUE THREAD

**Issue by ThereseLindblom** [ThereseLindblom/su-mt4007#1]

**Comment by Schwankus** [comment]
Hello!

Interesting that you spin your own yarn! I wasn't aware that was a hobby, but I see how fun it could be.

The only critique for this homework is that the notebook file and the folder containing it should technically both be called "HW1", but that is just a little nitpick. Other that that you did all you were supposed to!

**Comment by bettyfranklamanuens** [comment]
# Passed

Welcome to the course!
